name = "worker-rust"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "RUSTFLAGS='-C target-feature=+simd128' cargo install -q worker-build && worker-build --release"
